# -*- coding: utf-8 -*-
"""EDA Project(Draft I).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OS9Wu65Mw9p96X4qXaDaV2B1XdiahWsV

# **Project Name**    -

##### **Project Type**    - EDA
##### **Contribution**    - Team
##### **Team Member 1 -** Shashank Chavan
##### **Team Member 2 -** 
##### **Team Member 3 -**
##### **Team Member 4 -**

# **Project Summary -**

Write the summary here within 500-600 words.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

**Write Problem Statement Here.**

#### **Define Your Business Objective?**

Answer Here.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required. 
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits. 
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule. 

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

"""### Dataset Loading"""

from google.colab import drive
drive.mount('/content/drive')

# Load Dataset
df = pd.read_csv('/content/drive/MyDrive/Cohort Venice/EDA project/Global Terrorism Data.csv', encoding = ('ISO-8859-1'), low_memory=False)

"""### Dataset First View"""

# Dataset First Look
df.head()

df.tail()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
df.shape

df.columns

"""### Dataset Information"""

# Dataset Info
df.info()

df.describe().T

"""**Let us create a new dataset with columns we want to work upon**"""

df_new = df[['eventid','iyear','imonth','iday','country_txt','region_txt','city','multiple', 'success','attacktype1_txt','targtype1_txt','nkill','weapdetail','nwound', 'claimed','gname','provstate']].copy()

df_new.rename(columns={'eventid':'id','iyear':'year','imonth':'month','iday':'day','country_txt':'country','region_txt':'region','attacktype1_txt':'attack_type','targtype1_txt':'target_type','nkill':'fatalities','weapdetail':'weapon_detail','nwound':'wounded','gname':'perpetrator'}, inplace = True)

df_new.head(25)

df_new.info()

df_new.describe()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
#df_new.duplicated().sum()
len(df_new[df_new.duplicated()])

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
df_new.isnull().sum()

# Visualizing the missing values
# Checking Null Value by plotting Heatmap
#sns.heatmap(heatmap(df_new.isnull(), cbar=False)

"""### What did you know about your dataset?

# **In the raw data set the number of rows are 181691 and columns are 135, we are going consider 17 columns out of 135 for further data manupulation and visualization. In this 17 columns duplicated data is not present and column named city, fatalities, weapon detail, wounded, claimed, provstate contins some null values.  **

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df_new.columns

# Dataset Describe
df_new.describe(include='all')

"""### Variables Description

Write column discription

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for i in df_new.columns.tolist():
  print("No. of unique values in ",i,"is",df_new[i].nunique(),".")

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
df1 = df_new.copy()

"""Year-wise attacks in the world """

worldwide_year_wise_attacks = df_new.groupby(['year', 'region']).agg({'id':'count'}).rename(columns={'id':'No_of_attacks'}).reset_index()
worldwide_year_wise_attacks

plt.scatter(y=worldwide_year_wise_attacks['region'], x=worldwide_year_wise_attacks['year'],s=100, c=worldwide_year_wise_attacks['No_of_attacks'], cmap=plt.cm.get_cmap('PiYG',15))
plt.xlabel('Year')
plt.ylabel('Region Attacked')
plt.title('Worldwide year-wise attacks')
plt.colorbar(orientation= 'horizontal', label= 'Number of attacks', extend = 'both')
plt.show()



"""# **Region-wise attack from year 1970-2017**"""

# Checking for the top 10 regions with the most number of attacks
df_region = df1[['region']].copy()
region_wise_attacks = df_region.groupby('region').agg({'region' : 'count'}).rename(columns = {'region' : 'total_attacks'}).sort_values('total_attacks', ascending=False)[:10].reset_index()

#region_wise_attacks.reset_index()
#region_wise_attacks['region'] = region_wise_attacks.index
region_wise_attacks

plt.rcParams['figure.figsize']=(15,7)
sns.set(font_scale=1.3)
sns.set_style('ticks')
ax=sns.barplot(x='total_attacks', y='region', data=region_wise_attacks, palette='crest')
ax.set_title("Region-Wise Terrorist Attack - Year 1970-2017",fontsize=25,fontweight='bold')
ax.set_xlabel('Total Attacks',fontsize=20)
ax.set_ylabel('Region',fontsize=20)

"""As the top three most affected regions are Middle East and North Africa, South asia and South america. Let us find out the most affected country in this top three affected regions. """

df_country = df1[['country', 'region', 'id']].copy()
affected_countries = df_country.groupby(['region', 'country']).agg({'id': 'count'}).rename(columns = {'id': 'total_attack'}).sort_values('total_attack', ascending = False).reset_index()
affected_countries[:20]

"""The most affected country in Middle East and North Africa is Iraq and in South asia it is pakistan.
Let us on each country one by one.
"""

df_iraq = df1[df1['country'] == 'Iraq'].copy()
df_pakistan = df1[df1['country'] == 'Pakistan'].copy()

"""Let us find out the target type in this two countries"""

#top 10 targets in Iraq 
target_in_iraq = df_iraq.groupby('target_type').agg({'target_type' : 'count'}).rename(columns = {'target_type' : 'total_attacks'}).sort_values('total_attacks',ascending = False).reset_index()
target_in_iraq

#top 10 targets in Pakistan 
target_in_pakistan = df_pakistan.groupby('target_type').agg({'target_type' : 'count'}).rename(columns = {'target_type' : 'total_attacks'}).sort_values('total_attacks',ascending = False).reset_index()
target_in_pakistan

sns.set(font_scale=1.3)
sns.set_style("ticks")
fig, axarr = plt.subplots(1,2, figsize=(25, 10))
a = sns.barplot(data=target_in_iraq.head(5), x='target_type', y='total_attacks', ax=axarr[0], palette='rocket')
a.set_title("Most Affected Targets in Iraq",fontsize=20,fontweight='bold')
a.set_xlabel('Target Type', fontsize=15)
a.set_ylabel('Total Attacks',fontsize=15)
b = sns.barplot(data=target_in_pakistan.head(5), x='target_type', y='total_attacks', ax=axarr[1], palette='rocket')
b.set_title("Most affected Targets in Pakistan",fontsize=20,fontweight='bold')
b.set_xlabel('Target Type',fontsize=15)
b.set_ylabel('Total Attacks',fontsize=15)

#target_in_iraq.head(11).plot.bar(ax=axarr[0])
#target_in_pakistan.head(11).plot.bar(ax=axarr[1])

"""Let us find out the most used weapons in these two countries  """

df_iraq.head()

null_iraq = df_iraq.isnull().sum()
null_iraq

non_null_iraq = df_iraq.dropna()
non_null_iraq.head()
non_null_iraq.isnull().sum()

null_pakistan = df_pakistan.isnull().sum()
null_pakistan
non_null_pakistan = null_pakistan.dropna()
non_null_pakistan.isnull().sum()

major_weapons_iraq = non_null_iraq.groupby('weapon_detail').agg({'id': 'count'}).sort_values('id', ascending = False).reset_index()
major_weapons_iraq

"""Which type of attack causes more damage in terms of fatalities and wounded people"""

df_iraq['damage'] = df_iraq['fatalities'] + df_iraq['wounded']
df_pakistan['damage'] = df_pakistan['fatalities'] + df_pakistan['wounded']
df_pakistan

col_to_work = ['id', 'attack_type', 'damage']
attack_damage_iraq = df_iraq.groupby('attack_type').agg({'damage':'sum','id': 'count'}).rename(columns = {'id': 'attack_count'}).sort_values('damage', ascending = False).reset_index()
attack_damage_iraq

attack_damage_pakistan = df_pakistan.groupby('attack_type').agg({'damage':'sum','id': 'count'}).rename(columns = {'id': 'attack_count'}).sort_values('damage', ascending = False).reset_index()
attack_damage_pakistan

pie_labels = ['Bombing/Explosion', 'Armed Assault', 'Hostage kidnapping', 'Unknown','Assassination',]
explode=[0.05,0,0,0,0]
plt.rcParams['figure.figsize']=(18,10)
plt.pie(attack_damage_iraq["attack_count"].head(5),labels=pie_labels,explode= explode, shadow=True, autopct='%1.1f%%')
plt.title('Total attacks in Iraq')
plt.axis('equal')
plt.show()

pie_labels = ['Bombing/Explosion', 'Armed Assault', 'Hostage kidnapping', 'Unknown','Assassination',]
explode=[0.05,0,0,0,0]
plt.rcParams['figure.figsize']=(18,10)
plt.pie(attack_damage_iraq["damage"].head(5),labels=pie_labels,explode= explode, shadow=True, autopct='%1.1f%%')
plt.title('Total damage in Iraq due diffrent types of attacks')
plt.axis('equal')
plt.show()

pie_labels = ['Bombing/Explosion', 'Armed Assault','Assassination', 'Hostage kidnapping','Unknown']
explode=[0.05,0,0,0,0]
plt.rcParams['figure.figsize']=(18,10)
plt.pie(attack_damage_pakistan["attack_count"].head(5),labels=pie_labels,explode= explode, shadow=True, autopct='%1.1f%%')
plt.title('Total attacks in Pakistan')
plt.axis('equal')
plt.show()

pie_labels = ['Bombing/Explosion', 'Armed Assault','Assassination', 'Hostage kidnapping','Unknown']
explode=[0.05,0,0,0,0]
plt.rcParams['figure.figsize']=(18,10)
plt.pie(attack_damage_pakistan["damage"].head(5),labels=pie_labels,explode= explode, shadow=True, autopct='%1.1f%%')
plt.title('Total damage in Pakistan due diffrent types of attacks')
plt.axis('equal')
plt.show()

"""Top 5 terrorist group invovled in attacks in these countries"""

most_active_known_perpetrator_iraq = df_iraq.groupby('perpetrator').agg({'id': 'count'}).rename(columns = {'id':'No_of_attacks'}).sort_values('No_of_attacks', ascending = False)[1:7].reset_index()
most_active_known_perpetrator_iraq.head(5)

ax=plt.rcParams['figure.figsize'] = 16,8.27
ax=sns.barplot(data= most_active_known_perpetrator_iraq.head(5), x='perpetrator', y = 'No_of_attacks', palette = 'pastel')
ax.set_xlabel('Terrorist groups',fontsize=18)
plt.xticks(rotation = 75)
ax.set_ylabel('Number of Terrorist Attacks',fontsize=18)
ax.set_title('Top terrorist groups active in Iraq',fontsize=20);

most_active_known_perpetrator_pakistan = df_pakistan.groupby('perpetrator').agg({'id': 'count'}).rename(columns = {'id':'No_of_attacks'}).sort_values('No_of_attacks', ascending = False)[1:7].reset_index()
most_active_known_perpetrator_pakistan.head(6)

ax=plt.rcParams['figure.figsize'] = 16,8.27
ax=sns.barplot(data= most_active_known_perpetrator_pakistan.head(5), x='perpetrator', y = 'No_of_attacks', palette = 'pastel')
ax.set_xlabel('Terrorist groups',fontsize=18)
plt.xticks(rotation = 75)
ax.set_ylabel('Number of Terrorist Attacks',fontsize=18)
ax.set_title('Top terrorist groups active in Pakistan',fontsize=20);

"""### What all manipulations have you done and insights you found?

Answer Here.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 2
"""

# Chart - 2 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 3
"""

# Chart - 3 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 4
"""

# Chart - 4 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 5
"""

# Chart - 5 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 6
"""

# Chart - 6 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 7
"""

# Chart - 7 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 8
"""

# Chart - 8 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 9
"""

# Chart - 9 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 10
"""

# Chart - 10 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 11
"""

# Chart - 11 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 12
"""

# Chart - 12 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 13
"""

# Chart - 13 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ? 
Explain Briefly.

Answer Here.

# **Conclusion**

Write the conclusion here.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""